iipc/awesome-web-archiving

- README.md
Partially addresses #1 
@anjackson @atomotic let me know what you think. Happy to keep on chipping away at this.
> First pass at list structure.

- README.md
added html2warc, a simple script to convert offline data into a single warc file
> added html2warc

- README.md
A free variant of the already included "The Archive Browser" limited to the extraction features.
> Add "The Unarchiver" app.

- README.md
Partially in response to #22, this adds a few other links and attempts to explain the intention a bit.
> Add some links to other resources and clarifications

- README.md
I deliberated under which category this should fit but replay seems most appropriate. Also added a "-" for consistency to previous entry.
> Add InterPlanetary Wayback

- README.md
> Updates to PR#24 by @kant as recommended by @ruebot

- README.md
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/iipc/awesome-web-archiving#contribute) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent preserving the web. 🖖**
For more information about this crawler see the WSDL announcement [blog post](http://ws-dl.blogspot.com/2017/07/2017-07-24-replacing-heritrix-with.html) 
If the removal of the trailing whitespace (editor config) included in this PR is not desired I am more than happy to amend the commit.
> Add Squidwarc to the list

- README.md
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/iipc/awesome-web-archiving#contribute) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent preserving the web. 🖖**
I updated `node-warcs` entry in the list to reflect the [WSDL blog post](http://ws-dl.blogspot.com/2017/07/2017-07-24-replacing-heritrix-with.html) about it and WAILs + Squidwarcs usage of this library
> Updated node-warcs entry in the list 

- README.md
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/iipc/awesome-web-archiving#contribute) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent preserving the web. 🖖**
Add `node-cdxj` per the WSDL announcement [blog post](http://ws-dl.blogspot.com/2017/07/2017-07-24-replacing-heritrix-with.html)
> Add node-cdxj to the list

- README.md
As @ruebot has now created a sign-up form, changing from contacting @ianmilligan1 to using the Google Form.
> Updating Archives Unleashed Slack signup

- README.md
> Added httpreserve.info

- README.md
https://github.com/httpreserve/tikalinkextract
> Added HTTPreserve tikalinkextract.

- README.md
https://github.com/httpreserve/workbench
> Added HTTPreserve Workbench

- README.md
No need to link them twice, right next to each other! 😅
> removes duplicate link to awesome-momento

- README.md
> Add ArchiveTools per #42

- README.md
Also see this comment thread for more: https://www.reddit.com/r/DataHoarder/comments/85hsnl/trying_to_make_a_comprehensive_list_of_all_the/
**GUI/web UI:**
- Pocket premium
- Pinboard premium
- [Bookmark Archiver](https://github.com/pirate/bookmark-archiver/) a self-hosted way-back machine that produces a static html archive
- [Memex by Worldbrain.io](https://github.com/WorldBrain/Memex) a browser extension that saves all your history and does full-text search
- [Hypothes.is](https://web.hypothes.is/) a web/pdf/ebook annotation tool that also archives content
- [Perkeep](https://perkeep.org/) "Perkeep lets you permanently keep your stuff, for life."
- [Fetching.io](http://fetching.io/) A personal search engine/archiver that lets you search through all archived websites that you've …
> Add Bookmark-Archiver

- README.md
Is it a good idea to have a separate section dedicated to working with publishers to make the original websites as friendly to archiving as possible?
> Create section for guidance for web publishers

- README.md
Full disclosure: I’m the author.
> Add crocoite

- README.md
Adding some QA tools, based initially on recommendations from Kourosh from the UK National Archives.
> Adding a QA section & more detailed TOC

- README.md
> Add WebMemex

- README.md
See https://github.com/gildas-lormeau/SingleFile
> Add SingleFile

- README.md
MemGator has been around for a while, which is being utilized in many other tools/services and in research tasks.
> Add MemGator to the list of utilities

- README.md
This is an evolution of the Archive Profiling work.
> Add MementoMap to the list of utilities

- .github/workflows/lint.yml
This will ensure that future changes to the list adhere to the awesome linting guidelines.
> Add GH Workflow Action for automated linting

- CONTRIBUTING.md
- LICENSE
- README.md
- deprecated.md
This will allow us to work towards closing #48.
> Fix awesome lint issues

- README.md
Should this category be sorted like other categories?
> Add Reconstructive

- README.md
I think DSHR's blog is a good resource to add here.
> Add DSHR Blog

- README.md
Thanks @ruebot for catching this one.
> Fix a typo in #87

- CONTRIBUTING.md
- README.md
These changes are made to comply with the comments at https://github.com/sindresorhus/awesome/pull/1704#issuecomment-602161428 in order to close #48.
> Elaborate description and make tags italic

- README.md
Adding the results of the GLAM Workbench work and re-jigging to 
make clearer links to other community resources. 
Also added a link to the Web Archiving Community list.
> Adding GLAM Workbench and Awesome Lists section

- README.md
Full disclosure: I am one of the authors of ipwb and by no means am attempting to promote it with this change, but figured the consistency would be appreciated.
> Sort Replay section alphabetically to align with other sections

- README.md
Cairn: https://github.com/wabarc/cairn
Obelisk: https://github.com/go-shiori/obelisk
> Add Cairn and Obelisk to the list.

- README.md
> Notice about 22120

- README.md
added @WebSciDL to the Twitter list.
> added @WebSciDL

- README.md
I also tried to normalize capitalization of Chrome :-) 
Note: I wasn't sure whether to designate Stable or In Development. Mostly because something can be stable while it's being actively developed, and also because I saw those terms didn't seem to be universally applied.
> Added Browsertrix and ArchiveWeb.page

- README.md
Also moved WAIL up the list to correct alphabetical order.
> Add Warcprox

- README.md
WCT should clearly be on this list.
The curation section is a proposal to capture any tools that integrate web archiving into curation workflows and tools.
> Adding WCT and a  separate curation section.

- README.md
(BTW, the have quite a lot of interesting looking projects https://github.com/nlnwa ...)
> Add gowarcserver by Norsk nettarkiv

- README.md
https://arxiv.org/abs/2112.03103
> Add FastWARC

- README.md
link:  <https://github.com/akamhy/waybackpy>
> Add waybackpy

- README.md
> Update URI for SiteStory

- README.md
Adding warcat-rs which seems to be still in development.
> Add warcat-rs

- README.md
Adding hyphe, following yesterday's webinar and Olga's suggestion
> Update README.md (add hyphe tool from médialab)

- README.md
This looks like an incredible resource and looks like a great ecosystem I was shown by @gchartier today.
> Add Community Archive (Twitter Archive and API)
